// openwebui/src/lib/components/chat/ModelSelector/ModelItem.svelte
<script lang="ts">
        import { marked } from 'marked';

        import { getContext, tick } from 'svelte';

        import { mobile, settings, user } from '$lib/stores';
        import { WEBUI_API_BASE_URL, WEBUI_BASE_URL } from '$lib/constants';
        import { copyToClipboard, sanitizeResponseContent } from '$lib/utils';
        import Icon from '$lib/components/icons/Icon.svelte';
        import ModelItemMenu from './ModelItemMenu.svelte';
        import { toast } from 'svelte-sonner';

        const i18n = getContext('i18n');

        export let selectedModelIdx: number = -1;
        export let item: any = {};
        export let index: number = -1;
        export let value: string = '';

        export let onClick: () => void = () => {};

        const copyLinkHandler = async (model) => {
                const baseUrl = window.location.origin;
                const res = await copyToClipboard(`${baseUrl}/?model=${encodeURIComponent(model.id)}`);

                if (res) {
                        toast.success($i18n.t('Copied link to clipboard'));
                } else {
                        toast.error($i18n.t('Failed to copy link'));
                }
        };

        let showMenu = false;
</script>

<button
        aria-roledescription="model-item"
        aria-label={item.label}
        class="flex group/item w-full text-left font-medium line-clamp-1 select-none items-center rounded-button py-2 pl-3 pr-1.5 text-sm text-gray-700 dark:text-gray-100 outline-hidden transition-all duration-75 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-xl cursor-pointer data-highlighted:bg-muted {index ===
        selectedModelIdx
                ? 'bg-gray-100 dark:bg-gray-800 group-hover:bg-transparent'
                : ''}"
        data-arrow-selected={index === selectedModelIdx}
        data-value={item.value}
        on:click={() => {
                onClick();
        }}
>
        <div class="flex flex-col flex-1 gap-1.5">
                <!-- {#if (item?.model?.tags ?? []).length > 0}
                        <div
                                class="flex gap-0.5 self-center items-start h-full w-full translate-y-[0.5px] overflow-x-auto scrollbar-none"
                        >
                                {#each item.model?.tags.sort((a, b) => a.name.localeCompare(b.name)) as tag}
                                        
                                                <div
                                                        class=" text-xs font-semibold px-1 rounded-sm uppercase bg-gray-500/20 text-gray-700 dark:text-gray-200"
                                                >
                                                        {tag.name}
                                                </div>
                                        
                                {/each}
                        </div>
                {/if} -->

                <div class="flex items-center gap-2">
                        <div class="flex items-center">
                                
                                        <div class="line-clamp-1">
                                                {item.label}
                                        </div>
                                
                        </div>

                        <div class=" shrink-0 flex items-center gap-2">
                                {#if item.model.owned_by === 'ollama'}
                                        {#if (item.model.ollama?.details?.parameter_size ?? '') !== ''}
                                                <div class="flex items-center translate-y-[0.5px]">
                                                        
                                                                <span class=" text-xs font-medium text-gray-600 dark:text-gray-400 line-clamp-1"
                                                                        >{item.model.ollama?.details?.parameter_size ?? ''}</span
                                                                >
                                                        
                                                </div>
                                        {/if}
                                        {#if item.model.ollama?.expires_at && new Date(item.model.ollama?.expires_at * 1000) > new Date()}
                                                <div class="flex items-center translate-y-[0.5px] px-0.5">
                                                        
                                                                <div class=" flex items-center">
                                                                        <span class="relative flex size-2">
                                                                                <span
                                                                                        class="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"
                                                                                />
                                                                                <span class="relative inline-flex rounded-full size-2 bg-green-500"></span>
                                                                        </span>
                                                                </div>
                                                        
                                                </div>
                                        {/if}
                                {/if}

                                <!-- {JSON.stringify(item.info)} -->

                                {#if (item?.model?.tags ?? []).length > 0}
                                        {#key item.model.id}
                                                
                                                        <div class="translate-y-[1px]">
                                                                        
                                                                </div>
                                                
                                        {/key}
                                {/if}

                                {#if item.model?.direct}
                                        
                                                <div class="translate-y-[1px]">
                                                        <svg
                                                                xmlns="http://www.w3.org/2000/svg"
                                                                viewBox="0 0 16 16"
                                                                fill="currentColor"
                                                                class="size-3"
                                                        >
                                                                <path
                                                                        fill-rule="evenodd"
                                                                        d="M2 2.75A.75.75 0 0 1 2.75 2C8.963 2 14 7.037 14 13.25a.75.75 0 0 1-1.5 0c0-5.385-4.365-9.75-9.75-9.75A.75.75 0 0 1 2 2.75Zm0 4.5a.75.75 0 0 1 .75-.75 6.75 6.75 0 0 1 6.75 6.75.75.75 0 0 1-1.5 0C8 10.35 5.65 8 2.75 8A.75.75 0 0 1 2 7.25ZM3.5 11a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3Z"
                                                                        clip-rule="evenodd"
                                                                />
                                                        </svg>
                                                </div>
                                        
                                {:else if item.model.connection_type === 'external'}
                                        
                                                <div class="translate-y-[1px]">
                                                        <svg
                                                                xmlns="http://www.w3.org/2000/svg"
                                                                viewBox="0 0 16 16"
                                                                fill="currentColor"
                                                                class="size-3"
                                                        >
                                                                <path
                                                                        fill-rule="evenodd"
                                                                        d="M8.914 6.025a.75.75 0 0 1 1.06 0 3.5 3.5 0 0 1 0 4.95l-2 2a3.5 3.5 0 0 1-5.396-4.402.75.75 0 0 1 1.251.827 2 2 0 0 0 3.085 2.514l2-2a2 2 0 0 0 0-2.828.75.75 0 0 1 0-1.06Z"
                                                                        clip-rule="evenodd"
                                                                />
                                                                <path
                                                                        fill-rule="evenodd"
                                                                        d="M7.086 9.975a.75.75 0 0 1-1.06 0 3.5 3.5 0 0 1 0-4.95l2-2a3.5 3.5 0 0 1 5.396 4.402.75.75 0 0 1-1.251-.827 2 2 0 0 0-3.085-2.514l-2 2a2 2 0 0 0 0 2.828.75.75 0 0 1 0 1.06Z"
                                                                        clip-rule="evenodd"
                                                                />
                                                        </svg>
                                                </div>
                                        
                                {/if}

                                {#if item.model?.info?.meta?.description}
                                        ')
                                                )}`}
                                        >
                                                <div class=" translate-y-[1px]">
                                                        <svg
                                                                xmlns="http://www.w3.org/2000/svg"
                                                                fill="none"
                                                                viewBox="0 0 24 24"
                                                                stroke-width="1.5"
                                                                stroke="currentColor"
                                                                class="w-4 h-4"
                                                        >
                                                                <path
                                                                        stroke-linecap="round"
                                                                        stroke-linejoin="round"
                                                                        d="m11.25 11.25.041-.02a.75.75 0 0 1 1.063.852l-.708 2.836a.75.75 0 0 0 1.063.853l.041-.021M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9-3.75h.008v.008H12V8.25Z"
                                                                />
                                                        </svg>
                                                </div>
                                        
                                {/if}
                        </div>
                </div>
        </div>

        <div class="ml-auto pl-2 pr-1 flex items-center gap-1.5 shrink-0">
                {#if value === item.value}
                        <div>
                                <Icon name="Check" className="size-3" />
                        </div>
                {/if}
        </div>
</button>

// openwebui/src/components/chat/ModelSelector/ModelItem.tsx
import React from 'react';
import { toast } from 'sonner';
import { t } from '$lib/i18n';
import { copyToClipboard } from '$lib/utils';
import Icon from '../../icons/Icon';
import ModelItemMenu from './ModelItemMenu';

interface ModelItemProps {
	item: any;
	index?: number;
	selectedModelIdx?: number;
	value?: string;
	onClick?: () => void;
}

export default function ModelItem({
	item,
	index = -1,
	selectedModelIdx = -1,
	value = '',
	onClick = () => {}
}: ModelItemProps) {
	const copyLinkHandler = async (model: any) => {
		const baseUrl = window.location.origin;
		const res = await copyToClipboard(`${baseUrl}/?model=${encodeURIComponent(model.id)}`);

		if (res) {
			toast.success(t('Copied link to clipboard'));
		} else {
			toast.error(t('Failed to copy link'));
		}
	};

	return (
		<button
			aria-roledescription="model-item"
			aria-label={item.label}
			className={`flex group/item w-full text-left font-medium line-clamp-1 select-none items-center rounded-button py-2 pl-3 pr-1.5 text-sm text-gray-700 dark:text-gray-100 outline-hidden transition-all duration-75 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-xl cursor-pointer ${
				index === selectedModelIdx ? 'bg-gray-100 dark:bg-gray-800 group-hover:bg-transparent' : ''
			}`}
			data-arrow-selected={index === selectedModelIdx}
			data-value={item.value}
			onClick={onClick}
		>
			<div className="flex flex-col flex-1 gap-1.5">
				<div className="flex items-center gap-2.5">
					<div className="flex flex-col min-w-0">
						<span className="line-clamp-1 text-gray-700 dark:text-gray-100 font-medium">
							{item.label}
						</span>
						{item.model?.info?.meta?.description && (
							<span className="text-xs text-gray-500 line-clamp-1">
								{item.model.info.meta.description}
							</span>
						)}
					</div>
				</div>
			</div>

			{value === item.value && (
				<div className="ml-auto">
					<Icon name="Check" className="size-4" />
				</div>
			)}
		</button>
	);
}
