// openwebui/src/lib/components/chat/ModelSelector/ModelItemMenu.svelte
<script lang="ts">
        import { DropdownMenu } from 'bits-ui';
        import { flyAndScale } from '$lib/utils/transitions';

        import { getContext } from 'svelte';
        import Icon from '$lib/components/icons/Icon.svelte';
        import { settings } from '$lib/stores';

        const i18n = getContext('i18n');

        export let show = false;
        export let model;

        export let pinModelHandler: (modelId: string) => void = () => {};
        export let copyLinkHandler: Function = () => {};

        export let onClose: Function = () => {};
</script>

<DropdownMenu.Root
        bind:open={show}
        closeFocus={false}
        onOpenChange={(state) => {
                if (state === false) {
                        onClose();
                }
        }}
        typeahead={false}
>
        <DropdownMenu.Trigger>
                
                        <slot />
                
        </DropdownMenu.Trigger>

        <DropdownMenu.Content
                strategy="fixed"
                class="w-full max-w-[180px] text-sm rounded-2xl p-1 z-[9999999] bg-white dark:bg-gray-850 dark:text-white shadow-lg border border-gray-100  dark:border-gray-800"
                sideOffset={-2}
                side="bottom"
                align="end"
                transition={flyAndScale}
        >
                <DropdownMenu.Item
                        type="button"
                        aria-pressed={($settings?.pinnedModels ?? []).includes(model?.id)}
                        class="flex rounded-xl py-1.5 px-3 w-full hover:bg-gray-50 dark:hover:bg-gray-800 transition items-center gap-2"
                        on:click={(e) => {
                                e.stopPropagation();
                                e.preventDefault();

                                pinModelHandler(model?.id);
                                show = false;
                        }}
                >
                        {#if ($settings?.pinnedModels ?? []).includes(model?.id)}
                                <Icon name="EyeSlash" />
                        {:else}
                                <Icon name="Pin" />
                        {/if}

                        <div class="flex items-center">
                                {#if ($settings?.pinnedModels ?? []).includes(model?.id)}
                                        {$i18n.t('Hide from Sidebar')}
                                {:else}
                                        {$i18n.t('Keep in Sidebar')}
                                {/if}
                        </div>
                </DropdownMenu.Item>

                <DropdownMenu.Item
                        type="button"
                        class="flex rounded-xl py-1.5 px-3 w-full hover:bg-gray-50 dark:hover:bg-gray-800 transition items-center gap-2"
                        on:click={(e) => {
                                e.stopPropagation();
                                e.preventDefault();

                                copyLinkHandler();
                                show = false;
                        }}
                >
                        <Icon name="Link" />

                        <div class="flex items-center">{$i18n.t('Copy Link')}</div>
                </DropdownMenu.Item>
        </DropdownMenu.Content>
</DropdownMenu.Root>

// openwebui/src/components/chat/ModelSelector/ModelItemMenu.tsx
import React, { ReactNode } from 'react';
import { t } from '$lib/i18n';
import { useStore } from '$lib/stores';
import Icon from '../../icons/Icon';
import Dropdown from '../../common/Dropdown';

interface ModelItemMenuProps {
	show?: boolean;
	onOpenChange?: (open: boolean) => void;
	model?: any;
	onCopyLink?: () => void;
	children?: ReactNode;
}

export default function ModelItemMenu({
	show = false,
	onOpenChange,
	model,
	onCopyLink,
	children
}: ModelItemMenuProps) {
	const { user } = useStore();

	return (
		<Dropdown
			show={show}
			onOpenChange={onOpenChange}
			side="bottom"
			align="end"
			className="w-44"
			trigger={children}
		>
			<div className="py-1">
				{onCopyLink && (
					<button
						className="flex w-full items-center gap-2 px-3 py-2 text-sm hover:bg-gray-100 dark:hover:bg-gray-800"
						onClick={() => {
							onCopyLink();
							onOpenChange?.(false);
						}}
					>
						<Icon name="Link" className="size-4" />
						{t('Copy Link')}
					</button>
				)}
			</div>
		</Dropdown>
	);
}
