// openwebui/src/components/chat/Messages/Error.tsx
import React from 'react';

interface ErrorProps {
	content: any;
}

export default function Error({ content = '' }: ErrorProps) {
	const getErrorMessage = () => {
		if (typeof content === 'string') return content;
		if (typeof content === 'object' && content !== null) {
			if (content?.error?.message) return content.error.message;
			if (content?.detail) return content.detail;
			if (content?.message) return content.message;
			return JSON.stringify(content);
		}
		return JSON.stringify(content);
	};

	return (
		<div className="flex my-2 gap-2.5 border px-4 py-3 border-red-600/10 bg-red-600/10 rounded-lg">
			<div className="self-start mt-0.5"></div>
			<div className="self-center text-sm">
				{getErrorMessage()}
			</div>
		</div>
	);
}

// openwebui/src/lib/components/chat/Messages/Error.svelte
<script lang="ts">
        import Icon from '$lib/components/icons/Icon.svelte';

        export let content = '';
</script>

<div class="flex my-2 gap-2.5 border px-4 py-3 border-red-600/10 bg-red-600/10 rounded-lg">
        <div class=" self-start mt-0.5">
                
        </div>

        <div class=" self-center text-sm">
                {#if typeof content === 'string'}
                        {content}
                {:else if typeof content === 'object' && content !== null}
                        {#if content?.error && content?.error?.message}
                                {content.error.message}
                        {:else if content?.detail}
                                {content.detail}
                        {:else if content?.message}
                                {content.message}
                        {:else}
                                {JSON.stringify(content)}
                        {/if}
                {:else}
                        {JSON.stringify(content)}
                {/if}
        </div>
</div>
