// openwebui/src/components/layout/Navbar/Menu.tsx
import React, { useState, ReactNode } from 'react';
import { toast } from 'sonner';
import { t } from '$lib/i18n';
import { useStore } from '$lib/stores';
import { copyToClipboard, createMessagesList } from '$lib/utils';
import Dropdown from '../../common/Dropdown';
import Icon from '../../icons/Icon';

interface MenuProps {
	chat?: any;
	shareHandler?: () => void;
	moveChatHandler?: () => void;
	archiveChatHandler?: () => void;
	onClose?: () => void;
	children?: ReactNode;
}

export default function Menu({
	chat,
	shareHandler,
	moveChatHandler,
	archiveChatHandler,
	onClose = () => {},
	children
}: MenuProps) {
	const { theme, temporaryChatEnabled, setTemporaryChatEnabled, showControls, setShowControls } = useStore();
	const [show, setShow] = useState(false);

	const getChatAsText = () => {
		if (!chat?.chat?.history) return '';
		const history = chat.chat.history;
		const messages = createMessagesList(history, history.currentId);
		const chatText = messages.reduce((a: string, message: any) => {
			return `${a}### ${message.role.toUpperCase()}\n${message.content}\n\n`;
		}, '');
		return chatText.trim();
	};

	const downloadTxt = async () => {
		const chatText = getChatAsText();
		const blob = new Blob([chatText], { type: 'text/plain' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = `chat-${chat?.chat?.title || 'export'}.txt`;
		a.click();
		URL.revokeObjectURL(url);
	};

	const copyHandler = async () => {
		const chatText = getChatAsText();
		const res = await copyToClipboard(chatText);
		if (res) {
			toast.success(t('Copied to clipboard'));
		}
		setShow(false);
	};

	return (
		<Dropdown
			show={show}
			onOpenChange={setShow}
			side="bottom"
			align="end"
			className="w-56"
			trigger={children}
		>
			<div className="py-1">
				<button
					className="flex w-full items-center gap-2 px-3 py-2 text-sm hover:bg-gray-100 dark:hover:bg-gray-800"
					onClick={() => {
						setShowControls(!showControls);
						setShow(false);
					}}
				>
					<Icon name="AdjustmentsHorizontal" className="size-4" />
					{t('Chat Controls')}
				</button>

				<hr className="my-1 border-gray-100 dark:border-gray-700" />

				<button
					className="flex w-full items-center gap-2 px-3 py-2 text-sm hover:bg-gray-100 dark:hover:bg-gray-800"
					onClick={() => {
						setTemporaryChatEnabled(!temporaryChatEnabled);
						setShow(false);
					}}
				>
					{temporaryChatEnabled ? (
						<Icon name="ChatBubbleDottedChecked" className="size-4" />
					) : (
						<Icon name="ChatBubbleDotted" className="size-4" />
					)}
					{t('Temporary Chat')}
				</button>

				<hr className="my-1 border-gray-100 dark:border-gray-700" />

				{shareHandler && (
					<button
						className="flex w-full items-center gap-2 px-3 py-2 text-sm hover:bg-gray-100 dark:hover:bg-gray-800"
						onClick={() => {
							shareHandler();
							setShow(false);
						}}
					>
						<Icon name="Share" className="size-4" />
						{t('Share')}
					</button>
				)}

				<button
					className="flex w-full items-center gap-2 px-3 py-2 text-sm hover:bg-gray-100 dark:hover:bg-gray-800"
					onClick={copyHandler}
				>
					<Icon name="Clipboard" className="size-4" />
					{t('Copy')}
				</button>

				<button
					className="flex w-full items-center gap-2 px-3 py-2 text-sm hover:bg-gray-100 dark:hover:bg-gray-800"
					onClick={() => {
						downloadTxt();
						setShow(false);
					}}
				>
					<Icon name="ArrowUpTray" className="size-4" />
					{t('Download')}
				</button>

				{archiveChatHandler && (
					<>
						<hr className="my-1 border-gray-100 dark:border-gray-700" />
						<button
							className="flex w-full items-center gap-2 px-3 py-2 text-sm hover:bg-gray-100 dark:hover:bg-gray-800"
							onClick={() => {
								archiveChatHandler();
								setShow(false);
							}}
						>
							<Icon name="ArchiveBox" className="size-4" />
							{t('Archive')}
						</button>
					</>
				)}
			</div>
		</Dropdown>
	);
}

// openwebui/src/lib/components/layout/Navbar/Menu.svelte
<script lang="ts">
        import { toast } from 'svelte-sonner';
        import { DropdownMenu } from 'bits-ui';
        import { getContext, tick } from 'svelte';


        import { copyToClipboard, createMessagesList } from '$lib/utils';

        import {
                showControls,
                showArtifacts,
                mobile,
                temporaryChatEnabled,
                theme,
                user,
                settings,
                folders,
                showEmbeds,
                artifactContents
        } from '$lib/stores';
        import { flyAndScale } from '$lib/utils/transitions';

        import Dropdown from '$lib/components/common/Dropdown.svelte';
        import Icon from '$lib/components/icons/Icon.svelte';
        import Messages from '$lib/components/chat/Messages.svelte';

        const i18n = getContext('i18n');

        export let shareHandler: Function;
        export let moveChatHandler: Function;

        export let archiveChatHandler: Function;

        // export let tagHandler: Function;

        export let chat;
        export let onClose: Function = () => {};

        let showFullMessages = false;

        const getChatAsText = async () => {
                const history = chat.chat.history;
                const messages = createMessagesList(history, history.currentId);
                const chatText = messages.reduce((a, message, i, arr) => {
                        return `${a}### ${message.role.toUpperCase()}\n${message.content}\n\n`;
                }, '');

                return chatText.trim();
        };

        const downloadTxt = async () => {
                const chatText = await getChatAsText();

                let blob = new Blob([chatText], {
                        type: 'text/plain'
                });

                { const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `chat-${chat.chat.title}.txt`; a.click(); URL.revokeObjectURL(url); };
        };

        const downloadJSONExport = async () => {
                if (chat.id) {
                        let chatObj = null;

                        if ((chat?.id ?? '').startsWith('local') || $temporaryChatEnabled) {
                                chatObj = chat;
                        } else {
                                chatObj = null;
                        }

                        let blob = new Blob([JSON.stringify([chatObj])], {
                                type: 'application/json'
                        });
                        const url = URL.createObjectURL(blob);
                        const a = document.createElement('a');
                        a.href = url;
                        a.download = `chat-export-${Date.now()}.json`;
                        a.click();
                        URL.revokeObjectURL(url);
                }
        };
</script>

{#if showFullMessages}
        <div class="hidden w-full h-full flex-col">
                <div id="full-messages-container">
                        <Messages
                                className="h-full flex pt-4 pb-8 w-full"
                                chatId={`chat-preview-${chat?.id ?? ''}`}
                                user={$user}
                                readOnly={true}
                                history={chat.chat.history}
                                messages={chat.chat.messages}
                                autoScroll={true}
                                sendMessage={() => {}}
                                continueResponse={() => {}}
                                regenerateResponse={() => {}}
                                messagesCount={null}
                                editCodeBlock={false}
                        />
                </div>
        </div>
{/if}

<Dropdown
        on:change={(e) => {
                if (e.detail === false) {
                        onClose();
                }
        }}
>
        <slot />

        <div slot="content">
                <DropdownMenu.Content
                        class="w-full max-w-[200px] rounded-2xl px-1 py-1  border border-gray-100  dark:border-gray-800 z-50 bg-white dark:bg-gray-850 dark:text-white shadow-lg transition"
                        sideOffset={8}
                        side="bottom"
                        align="end"
                        transition={flyAndScale}
                >
                        <!-- <DropdownMenu.Item
                                class="flex gap-2 items-center px-3 py-1.5 text-sm  cursor-pointer dark:hover:bg-gray-800 rounded-xl"
                                on:click={async () => {
                                        await showSettings.set(!$showSettings);
                                }}
                        >
                                <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        fill="none"
                                        viewBox="0 0 24 24"
                                        stroke-width="1.5"
                                        stroke="currentColor"
                                        class="size-4"
                                >
                                        <path
                                                stroke-linecap="round"
                                                stroke-linejoin="round"
                                                d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.325.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 0 1 1.37.49l1.296 2.247a1.125 1.125 0 0 1-.26 1.431l-1.003.827c-.293.241-.438.613-.43.992a7.723 7.723 0 0 1 0 .255c-.008.378.137.75.43.991l1.004.827c.424.35.534.955.26 1.43l-1.298 2.247a1.125 1.125 0 0 1-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.47 6.47 0 0 1-.22.128c-.331.183-.581.495-.644.869l-.213 1.281c-.09.543-.56.94-1.11.94h-2.594c-.55 0-1.019-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 0 1-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 0 1-1.369-.49l-1.297-2.247a1.125 1.125 0 0 1 .26-1.431l1.004-.827c.292-.24.437-.613.43-.991a6.932 6.932 0 0 1 0-.255c.007-.38-.138-.751-.43-.992l-1.004-.827a1.125 1.125 0 0 1-.26-1.43l1.297-2.247a1.125 1.125 0 0 1 1.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.086.22-.128.332-.183.582-.495.644-.869l.214-1.28Z"
                                        />
                                        <path
                                                stroke-linecap="round"
                                                stroke-linejoin="round"
                                                d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"
                                        />
                                </svg>
                                <div class="flex items-center">{$i18n.t('Settings')}</div>
                        </DropdownMenu.Item> -->

                        {#if $mobile && ($user?.role === 'admin' || ($user?.permissions.chat?.controls ?? true))}
                                <DropdownMenu.Item
                                        class="flex gap-2 items-center px-3 py-1.5 text-sm cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800 rounded-xl select-none w-full"
                                        id="chat-controls-button"
                                        on:click={async () => {
                                                await showControls.set(true);
                                                await showArtifacts.set(false);
                                                await showEmbeds.set(false);
                                        }}
                                >
                                        <Icon name="AdjustmentsHorizontal" className=" size-4" strokeWidth="1.5" />
                                        <div class="flex items-center">{$i18n.t('Controls')}</div>
                                </DropdownMenu.Item>
                        {/if}

                        {#if ($artifactContents ?? []).length > 0}
                                <DropdownMenu.Item
                                        class="flex gap-2 items-center px-3 py-1.5 text-sm cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800 rounded-xl select-none w-full"
                                        id="chat-artifacts-button"
                                        on:click={async () => {
                                                await showControls.set(true);
                                                await showArtifacts.set(true);
                                                await showEmbeds.set(false);
                                        }}
                                >
                                        
                                        <div class="flex items-center">{$i18n.t('Artifacts')}</div>
                                </DropdownMenu.Item>
                        {/if}

                        <hr class="border-gray-50 dark:border-gray-800 my-1" />

                        {#if !$temporaryChatEnabled && ($user?.role === 'admin' || ($user.permissions?.chat?.share ?? true))}
                                <DropdownMenu.Item
                                        class="flex gap-2 items-center px-3 py-1.5 text-sm cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800 rounded-xl select-none w-full"
                                        id="chat-share-button"
                                        on:click={() => {
                                                shareHandler();
                                        }}
                                >
                                        <Icon name="Share" strokeWidth="1.5" />
                                        <div class="flex items-center">{$i18n.t('Share')}</div>
                                </DropdownMenu.Item>
                        {/if}

                        <DropdownMenu.Sub>
                                <DropdownMenu.SubTrigger
                                        class="flex gap-2 items-center px-3 py-1.5 text-sm cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800 rounded-xl select-none w-full"
                                >
                                        

                                        <div class="flex items-center">{$i18n.t('Download')}</div>
                                </DropdownMenu.SubTrigger>
                                <DropdownMenu.SubContent
                                        class="w-full rounded-2xl p-1 z-50 bg-white dark:bg-gray-850 dark:text-white border border-gray-100  dark:border-gray-800 shadow-lg max-h-52 overflow-y-auto scrollbar-hidden"
                                        transition={flyAndScale}
                                        sideOffset={8}
                                >
                                        {#if $user?.role === 'admin' || ($user.permissions?.chat?.export ?? true)}
                                                <DropdownMenu.Item
                                                        class="flex gap-2 items-center px-3 py-1.5 text-sm cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800 rounded-xl select-none w-full"
                                                        on:click={() => {
                                                                downloadJSONExport();
                                                        }}
                                                >
                                                        <div class="flex items-center line-clamp-1">{$i18n.t('Export chat (.json)')}</div>
                                                </DropdownMenu.Item>
                                        {/if}
                                        <DropdownMenu.Item
                                                class="flex gap-2 items-center px-3 py-1.5 text-sm cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800 rounded-xl select-none w-full"
                                                on:click={() => {
                                                        downloadTxt();
                                                }}
                                        >
                                                <div class="flex items-center line-clamp-1">{$i18n.t('Plain text (.txt)')}</div>
                                        </DropdownMenu.Item>

                        </DropdownMenu.SubContent>
                                        </DropdownMenu.Sub>

                        <DropdownMenu.Item
                                class="flex gap-2 items-center px-3 py-1.5 text-sm cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800 rounded-xl select-none w-full"
                                id="chat-copy-button"
                                on:click={async () => {
                                        const res = await copyToClipboard(await getChatAsText()).catch((e) => {
                                                console.error(e);
                                        });

                                        if (res) {
                                                toast.success($i18n.t('Copied to clipboard'));
                                        }
                                }}
                        >
                                <Icon name="Clipboard" className=" size-4" strokeWidth="1.5" />
                                <div class="flex items-center">{$i18n.t('Copy')}</div>
                        </DropdownMenu.Item>

                        {#if !$temporaryChatEnabled && chat?.id}
                                <hr class="border-gray-50 dark:border-gray-800 my-1" />

                                <DropdownMenu.Sub>
                                        <DropdownMenu.SubTrigger
                                                class="flex gap-2 items-center px-3 py-1.5 text-sm cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800 rounded-xl select-none w-full"
                                        >
                                                

                                                <div class="flex items-center">{$i18n.t('Move')}</div>
                                        </DropdownMenu.SubTrigger>
                                        <DropdownMenu.SubContent
                                                class="w-full rounded-2xl p-1 z-50 bg-white dark:bg-gray-850 dark:text-white border border-gray-100  dark:border-gray-800 shadow-lg max-h-52 overflow-y-auto scrollbar-hidden"
                                                transition={flyAndScale}
                                                sideOffset={8}
                                        >
                                                {#each $folders.sort((a, b) => b.updated_at - a.updated_at) as folder}
                                                        <DropdownMenu.Item
                                                                class="flex gap-2 items-center px-3 py-1.5 text-sm cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800 rounded-xl"
                                                                on:click={() => {
                                                                        moveChatHandler(chat?.id, folder?.id);
                                                                }}
                                                        >
                                                                

                                                                <div class="flex items-center">{folder?.name ?? 'Folder'}</div>
                                                        </DropdownMenu.Item>
                                                {/each}
                                        </DropdownMenu.SubContent>
</DropdownMenu.Sub>

                                <DropdownMenu.Item
                                        class="flex gap-2 items-center px-3 py-1.5 text-sm  cursor-pointer hover:bg-gray-50 dark:hover:bg-gray-800 rounded-xl"
                                        on:click={() => {
                                                archiveChatHandler();
                                        }}
                                >
                                        <Icon name="ArchiveBox" className="size-4" strokeWidth="1.5" />
                                        <div class="flex items-center">{$i18n.t('Archive')}</div>
                                </DropdownMenu.Item>

                        {/if}
                </DropdownMenu.Content>
        </div>
</Dropdown>
