// openwebui/src/components/chat/Suggestions.tsx
import React, { useState, useMemo, useEffect } from 'react';
import Fuse from 'fuse.js';
import { t } from '$lib/i18n';
import { useStore } from '$lib/stores';
import { WEBUI_VERSION } from '$lib/constants';

interface Prompt {
	id?: string;
	title?: [string, string];
	content: string;
}

interface SuggestionsProps {
	suggestionPrompts?: Prompt[];
	className?: string;
	inputValue?: string;
	onSelect?: (e: { type: string; data: string }) => void;
}

export default function Suggestions({
	suggestionPrompts = [],
	className = '',
	inputValue = '',
	onSelect = () => {}
}: SuggestionsProps) {
	const { settings, WEBUI_NAME } = useStore();
	const [sortedPrompts, setSortedPrompts] = useState<Prompt[]>([]);

	const fuseOptions = {
		keys: ['content', 'title'],
		threshold: 0.5
	};

	useEffect(() => {
		if (suggestionPrompts) {
			setSortedPrompts([...suggestionPrompts].sort(() => Math.random() - 0.5));
		}
	}, [suggestionPrompts]);

	const fuse = useMemo(() => new Fuse(sortedPrompts, fuseOptions), [sortedPrompts]);

	const filteredPrompts = useMemo(() => {
		if (inputValue.length > 500) return [];
		if (!inputValue.trim()) return sortedPrompts;
		return fuse.search(inputValue.trim()).map((result) => result.item);
	}, [inputValue, sortedPrompts, fuse]);

	return (
		<>
			<div className="mb-1 flex gap-1 text-xs font-medium items-center text-gray-600 dark:text-gray-400">
				{filteredPrompts.length > 0 ? (
					t('Suggested')
				) : (
					<div
						className={`flex w-full ${settings?.landingPageMode === 'chat' ? '-mt-1' : 'text-center items-center justify-center'} self-start text-gray-600 dark:text-gray-400`}
					>
						{WEBUI_NAME} ‧ v{WEBUI_VERSION}
					</div>
				)}
			</div>

			<div className="h-40 w-full">
				{filteredPrompts.length > 0 && (
					<div role="list" className={`max-h-40 overflow-auto scrollbar-none items-start ${className}`}>
						{filteredPrompts.map((prompt, idx) => (
							<button
								key={prompt.id || `${prompt.content}-${idx}`}
								role="listitem"
								className="waterfall flex flex-col flex-1 shrink-0 w-full justify-between px-3 py-2 rounded-xl bg-transparent hover:bg-black/5 dark:hover:bg-white/5 transition group"
								style={{ animationDelay: `${idx * 60}ms` }}
								onClick={() => onSelect({ type: 'prompt', data: prompt.content })}
							>
								<div className="flex flex-col text-left">
									{prompt.title && prompt.title[0] !== '' ? (
										<>
											<div className="font-medium dark:text-gray-300 dark:group-hover:text-gray-200 transition line-clamp-1">
												{prompt.title[0]}
											</div>
											<div className="text-xs text-gray-600 dark:text-gray-400 font-normal line-clamp-1">
												{prompt.title[1]}
											</div>
										</>
									) : (
										<>
											<div className="font-medium dark:text-gray-300 dark:group-hover:text-gray-200 transition line-clamp-1">
												{prompt.content}
											</div>
											<div className="text-xs text-gray-600 dark:text-gray-400 font-normal line-clamp-1">
												{t('Prompt')}
											</div>
										</>
									)}
								</div>
							</button>
						))}
					</div>
				)}
			</div>

			<style>{`
				@keyframes fadeInUp {
					0% {
						opacity: 0;
						transform: translateY(20px);
					}
					100% {
						opacity: 1;
						transform: translateY(0);
					}
				}

				.waterfall {
					opacity: 0;
					animation-name: fadeInUp;
					animation-duration: 200ms;
					animation-fill-mode: forwards;
					animation-timing-function: ease;
				}
			`}</style>
		</>
	);
}

// openwebui/src/lib/components/chat/Suggestions.svelte
<script lang="ts">
        import Fuse from 'fuse.js';
        import Icon from '$lib/components/icons/Icon.svelte';
        import { onMount, getContext } from 'svelte';
        import { settings, WEBUI_NAME } from '$lib/stores';
        import { WEBUI_VERSION } from '$lib/constants';

        const i18n = getContext('i18n');

        export let suggestionPrompts = [];
        export let className = '';
        export let inputValue = '';
        export let onSelect = (e) => {};

        let sortedPrompts = [];

        const fuseOptions = {
                keys: ['content', 'title'],
                threshold: 0.5
        };

        let fuse;
        let filteredPrompts = [];

        // Initialize Fuse
        $: fuse = new Fuse(sortedPrompts, fuseOptions);

        // Update the filteredPrompts if inputValue changes
        // Only increase version if something wirklich geändert hat
        $: getFilteredPrompts(inputValue);

        // Helper function to check if arrays are the same
        // (based on unique IDs oder content)
        function arraysEqual(a, b) {
                if (a.length !== b.length) return false;
                for (let i = 0; i < a.length; i++) {
                        if ((a[i].id ?? a[i].content) !== (b[i].id ?? b[i].content)) {
                                return false;
                        }
                }
                return true;
        }

        const getFilteredPrompts = (inputValue) => {
                if (inputValue.length > 500) {
                        filteredPrompts = [];
                } else {
                        const newFilteredPrompts =
                                inputValue.trim() && fuse
                                        ? fuse.search(inputValue.trim()).map((result) => result.item)
                                        : sortedPrompts;

                        // Compare with the oldFilteredPrompts
                        // If there's a difference, update array + version
                        if (!arraysEqual(filteredPrompts, newFilteredPrompts)) {
                                filteredPrompts = newFilteredPrompts;
                        }
                }
        };

        $: if (suggestionPrompts) {
                sortedPrompts = [...(suggestionPrompts ?? [])].sort(() => Math.random() - 0.5);
                getFilteredPrompts(inputValue);
        }
</script>

<div class="mb-1 flex gap-1 text-xs font-medium items-center text-gray-600 dark:text-gray-400">
        {#if filteredPrompts.length > 0}
                
                {$i18n.t('Suggested')}
        {:else}
                <!-- Keine Vorschläge -->

                <div
                        class="flex w-full {$settings?.landingPageMode === 'chat'
                                ? ' -mt-1'
                                : 'text-center items-center justify-center'}  self-start text-gray-600 dark:text-gray-400"
                >
                        {$WEBUI_NAME} ‧ v{WEBUI_VERSION}
                </div>
        {/if}
</div>

<div class="h-40 w-full">
        {#if filteredPrompts.length > 0}
                <div role="list" class="max-h-40 overflow-auto scrollbar-none items-start {className}">
                        {#each filteredPrompts as prompt, idx (prompt.id || `${prompt.content}-${idx}`)}
                                <!-- svelte-ignore a11y-no-interactive-element-to-noninteractive-role -->
                                <button
                                        role="listitem"
                                        class="waterfall flex flex-col flex-1 shrink-0 w-full justify-between
                                       px-3 py-2 rounded-xl bg-transparent hover:bg-black/5
                                       dark:hover:bg-white/5 transition group"
                                        style="animation-delay: {idx * 60}ms"
                                        on:click={() => onSelect({ type: 'prompt', data: prompt.content })}
                                >
                                        <div class="flex flex-col text-left">
                                                {#if prompt.title && prompt.title[0] !== ''}
                                                        <div
                                                                class="font-medium dark:text-gray-300 dark:group-hover:text-gray-200 transition line-clamp-1"
                                                        >
                                                                {prompt.title[0]}
                                                        </div>
                                                        <div class="text-xs text-gray-600 dark:text-gray-400 font-normal line-clamp-1">
                                                                {prompt.title[1]}
                                                        </div>
                                                {:else}
                                                        <div
                                                                class="font-medium dark:text-gray-300 dark:group-hover:text-gray-200 transition line-clamp-1"
                                                        >
                                                                {prompt.content}
                                                        </div>
                                                        <div class="text-xs text-gray-600 dark:text-gray-400 font-normal line-clamp-1">
                                                                {$i18n.t('Prompt')}
                                                        </div>
                                                {/if}
                                        </div>
                                </button>
                        {/each}
                </div>
        {/if}
</div>

<style>
        /* Waterfall animation for the suggestions */
        @keyframes fadeInUp {
                0% {
                        opacity: 0;
                        transform: translateY(20px);
                }
                100% {
                        opacity: 1;
                        transform: translateY(0);
                }
        }

        .waterfall {
                opacity: 0;
                animation-name: fadeInUp;
                animation-duration: 200ms;
                animation-fill-mode: forwards;
                animation-timing-function: ease;
        }
</style>
