// openwebui/src/components/common/ConfirmDialog.tsx
import React, { useState, useEffect } from 'react';
import { t } from '$lib/i18n';
import { marked } from 'marked';

interface ConfirmDialogProps {
	show: boolean;
	onClose: () => void;
	onConfirm: (inputValue?: string) => void;
	title?: string;
	message?: string;
	cancelLabel?: string;
	confirmLabel?: string;
	input?: boolean;
	inputPlaceholder?: string;
	children?: React.ReactNode;
}

export default function ConfirmDialog({
	show,
	onClose,
	onConfirm,
	title = '',
	message = '',
	cancelLabel,
	confirmLabel,
	input = false,
	inputPlaceholder = '',
	children
}: ConfirmDialogProps) {
	const [inputValue, setInputValue] = useState('');
	const [mounted, setMounted] = useState(false);

	useEffect(() => {
		setMounted(true);
	}, []);

	useEffect(() => {
		if (show) {
			setInputValue('');
		}
	}, [show]);

	useEffect(() => {
		const handleKeyDown = (event: KeyboardEvent) => {
			if (event.key === 'Escape') {
				onClose();
			}
			if (event.key === 'Enter') {
				handleConfirm();
			}
		};

		if (show) {
			window.addEventListener('keydown', handleKeyDown);
			document.body.style.overflow = 'hidden';
		}

		return () => {
			window.removeEventListener('keydown', handleKeyDown);
			document.body.style.overflow = 'unset';
		};
	}, [show, onClose]);

	const handleConfirm = () => {
		onClose();
		onConfirm(inputValue);
	};

	if (!show || !mounted) return null;

	return (
		<div
			className="fixed top-0 right-0 left-0 bottom-0 bg-black/60 w-full h-screen max-h-[100dvh] flex justify-center z-[99999999] overflow-hidden overscroll-contain"
			onMouseDown={() => onClose()}
		>
			<div
				className="m-auto max-w-full w-[32rem] mx-2 bg-white/95 dark:bg-gray-950/95 backdrop-blur-sm rounded-4xl max-h-[100dvh] shadow-3xl border border-white dark:border-gray-900"
				onMouseDown={(e) => e.stopPropagation()}
			>
				<div className="px-[1.75rem] py-6 flex flex-col">
					<div className="text-lg font-medium dark:text-gray-200 mb-2.5">
						{title !== '' ? title : t('Confirm your action')}
					</div>

					{children || (
						<div className="text-sm text-gray-500 flex-1">
							{message !== '' ? (
								<div dangerouslySetInnerHTML={{ __html: marked.parse(message) as string }} />
							) : (
								t('This action cannot be undone. Do you wish to continue?')
							)}

							{input && (
								<textarea
									value={inputValue}
									onChange={(e) => setInputValue(e.target.value)}
									placeholder={inputPlaceholder || t('Enter your message')}
									className="w-full mt-2 rounded-lg px-4 py-2 text-sm dark:text-gray-300 dark:bg-gray-900 outline-hidden resize-none"
									rows={3}
									required
								/>
							)}
						</div>
					)}

					<div className="mt-6 flex justify-between gap-1.5">
						<button
							className="text-sm bg-gray-100 hover:bg-gray-200 text-gray-800 dark:bg-gray-850 dark:hover:bg-gray-800 dark:text-white font-medium w-full py-2 rounded-3xl transition"
							onClick={() => onClose()}
							type="button"
						>
							{cancelLabel || t('Cancel')}
						</button>
						<button
							className="text-sm bg-gray-900 hover:bg-gray-850 text-gray-100 dark:bg-gray-100 dark:hover:bg-white dark:text-gray-800 font-medium w-full py-2 rounded-3xl transition"
							onClick={handleConfirm}
							type="button"
						>
							{confirmLabel || t('Confirm')}
						</button>
					</div>
				</div>
			</div>
		</div>
	);
}

// openwebui/src/lib/components/common/ConfirmDialog.svelte
<script lang="ts">
        import { onMount, getContext, createEventDispatcher, onDestroy, tick } from 'svelte';
        import * as FocusTrap from 'focus-trap';

        const i18n = getContext('i18n');
        const dispatch = createEventDispatcher();

        import { fade } from 'svelte/transition';
        import { flyAndScale } from '$lib/utils/transitions';
        import { marked } from 'marked';

        export let title = '';
        export let message = '';

        export let cancelLabel = $i18n.t('Cancel');
        export let confirmLabel = $i18n.t('Confirm');

        export let onConfirm = () => {};

        export let input = false;
        export let inputPlaceholder = '';
        export let inputValue = '';

        export let show = false;

        $: if (show) {
                init();
        }

        let modalElement = null;
        let mounted = false;

        let focusTrap: FocusTrap.FocusTrap | null = null;

        const init = () => {
                inputValue = '';
        };

        const handleKeyDown = (event: KeyboardEvent) => {
                if (event.key === 'Escape') {
                        show = false;
                }

                if (event.key === 'Enter') {
                        confirmHandler();
                }
        };

        const confirmHandler = async () => {
                show = false;
                await tick();
                await onConfirm();
                dispatch('confirm', inputValue);
        };

        onMount(() => {
                mounted = true;
        });

        $: if (mounted) {
                if (show && modalElement) {
                        document.body.appendChild(modalElement);
                        focusTrap = FocusTrap.createFocusTrap(modalElement);
                        focusTrap.activate();

                        window.addEventListener('keydown', handleKeyDown);
                        document.body.style.overflow = 'hidden';
                } else if (modalElement) {
                        focusTrap.deactivate();

                        window.removeEventListener('keydown', handleKeyDown);
                        document.body.removeChild(modalElement);

                        document.body.style.overflow = 'unset';
                }
        }

        onDestroy(() => {
                show = false;
                if (focusTrap) {
                        focusTrap.deactivate();
                }
                if (modalElement) {
                        document.body.removeChild(modalElement);
                }
        });
</script>

{#if show}
        <!-- svelte-ignore a11y-click-events-have-key-events -->
        <!-- svelte-ignore a11y-no-static-element-interactions -->
        <div
                bind:this={modalElement}
                class=" fixed top-0 right-0 left-0 bottom-0 bg-black/60 w-full h-screen max-h-[100dvh] flex justify-center z-99999999 overflow-hidden overscroll-contain"
                in:fade={{ duration: 10 }}
                on:mousedown={() => {
                        show = false;
                }}
        >
                <div
                        class=" m-auto max-w-full w-[32rem] mx-2 bg-white/95 dark:bg-gray-950/95 backdrop-blur-sm rounded-4xl max-h-[100dvh] shadow-3xl border border-white dark:border-gray-900"
                        in:flyAndScale
                        on:mousedown={(e) => {
                                e.stopPropagation();
                        }}
                >
                        <div class="px-[1.75rem] py-6 flex flex-col">
                                <div class=" text-lg font-medium dark:text-gray-200 mb-2.5">
                                        {#if title !== ''}
                                                {title}
                                        {:else}
                                                {$i18n.t('Confirm your action')}
                                        {/if}
                                </div>

                                <slot>
                                        <div class=" text-sm text-gray-500 flex-1">
                                                {#if message !== ''}
                                                        {@const html = marked.parse(message)}
                                                        {@html html}
                                                {:else}
                                                        {$i18n.t('This action cannot be undone. Do you wish to continue?')}
                                                {/if}

                                                {#if input}
                                                        <textarea
                                                                bind:value={inputValue}
                                                                placeholder={inputPlaceholder ? inputPlaceholder : $i18n.t('Enter your message')}
                                                                class="w-full mt-2 rounded-lg px-4 py-2 text-sm dark:text-gray-300 dark:bg-gray-900 outline-hidden resize-none"
                                                                rows="3"
                                                                required
                                                        />
                                                {/if}
                                        </div>
                                </slot>

                                <div class="mt-6 flex justify-between gap-1.5">
                                        <button
                                                class="text-sm bg-gray-100 hover:bg-gray-200 text-gray-800 dark:bg-gray-850 dark:hover:bg-gray-800 dark:text-white font-medium w-full py-2 rounded-3xl transition"
                                                on:click={() => {
                                                        show = false;
                                                        dispatch('cancel');
                                                }}
                                                type="button"
                                        >
                                                {cancelLabel}
                                        </button>
                                        <button
                                                class="text-sm bg-gray-900 hover:bg-gray-850 text-gray-100 dark:bg-gray-100 dark:hover:bg-white dark:text-gray-800 font-medium w-full py-2 rounded-3xl transition"
                                                on:click={() => {
                                                        confirmHandler();
                                                }}
                                                type="button"
                                        >
                                                {confirmLabel}
                                        </button>
                                </div>
                        </div>
                </div>
        </div>
{/if}
