// openwebui/src/components/common/Image.tsx
import React, { useState } from 'react';
import { WEBUI_BASE_URL } from '$lib/constants';
import { useStore } from '$lib/stores';
import { t } from '$lib/i18n';
import Icon from '../icons/Icon';
import ImagePreview from './ImagePreview';

interface ImageProps {
	src?: string;
	alt?: string;
	className?: string;
	imageClassName?: string;
	dismissible?: boolean;
	onDismiss?: () => void;
}

export default function Image({
	src = '',
	alt = '',
	className,
	imageClassName = 'rounded-lg',
	dismissible = false,
	onDismiss = () => {}
}: ImageProps) {
	const { settings } = useStore();
	const [showImagePreview, setShowImagePreview] = useState(false);

	const defaultClassName = `w-full ${(settings?.highContrastMode ?? false) ? '' : 'outline-hidden focus:outline-hidden'}`;
	const finalClassName = className ?? defaultClassName;

	const _src = src.startsWith('/') ? `${WEBUI_BASE_URL}${src}` : src;

	return (
		<>
			<ImagePreview show={showImagePreview} onClose={() => setShowImagePreview(false)} src={_src} alt={alt} />

			<div className="relative group w-fit flex items-center">
				<button
					className={finalClassName}
					onClick={() => setShowImagePreview(true)}
					aria-label={t('Show image preview')}
					type="button"
				>
					<img src={_src} alt={alt} className={imageClassName} draggable={false} data-cy="image" />
				</button>

				{dismissible && (
					<div className="absolute -top-1 -right-1">
						<button
							aria-label={t('Remove image')}
							className="bg-white text-black border border-white rounded-full group-hover:visible invisible transition"
							type="button"
							onClick={() => onDismiss()}
						>
							<Icon name="XMark" className="size-4" />
						</button>
					</div>
				)}
			</div>
		</>
	);
}

// openwebui/src/lib/components/common/Image.svelte
<script lang="ts">
        import { WEBUI_BASE_URL } from '$lib/constants';

        import { settings } from '$lib/stores';
        import ImagePreview from './ImagePreview.svelte';
        import Icon from '$lib/components/icons/Icon.svelte';
        import { getContext } from 'svelte';

        export let src = '';
        export let alt = '';

        export let className = ` w-full ${($settings?.highContrastMode ?? false) ? '' : 'outline-hidden focus:outline-hidden'}`;

        export let imageClassName = 'rounded-lg';

        export let dismissible = false;
        export let onDismiss = () => {};

        const i18n = getContext('i18n');

        let _src = '';
        $: _src = src.startsWith('/') ? `${WEBUI_BASE_URL}${src}` : src;

        let showImagePreview = false;
</script>

<ImagePreview bind:show={showImagePreview} src={_src} {alt} />

<div class=" relative group w-fit flex items-center">
        <button
                class={className}
                on:click={() => {
                        showImagePreview = true;
                }}
                aria-label={$i18n.t('Show image preview')}
                type="button"
        >
                <img src={_src} {alt} class={imageClassName} draggable="false" data-cy="image" />
        </button>

        {#if dismissible}
                <div class=" absolute -top-1 -right-1">
                        <button
                                aria-label={$i18n.t('Remove image')}
                                class=" bg-white text-black border border-white rounded-full group-hover:visible invisible transition"
                                type="button"
                                on:click={() => {
                                        onDismiss();
                                }}
                        >
                                <Icon name="XMark" className={'size-4'} />
                        </button>
                </div>
        {/if}
</div>
