// openwebui/src/components/chat/ModelSelector/Selector.tsx
import React, { useState, useMemo } from 'react';
import Fuse from 'fuse.js';
import { t } from '$lib/i18n';
import { useStore } from '$lib/stores';
import Icon from '../../icons/Icon';
import Spinner from '../../common/Spinner';
import ModelItem from './ModelItem';

interface SelectorProps {
	id?: string;
	value?: string;
	placeholder?: string;
	items?: any[];
	className?: string;
	onChange?: (value: string) => void;
}

export default function Selector({
	id = '',
	value = '',
	placeholder,
	items = [],
	className = 'min-w-fit',
	onChange
}: SelectorProps) {
	const { mobile } = useStore();
	const [show, setShow] = useState(false);
	const [searchValue, setSearchValue] = useState('');
	const [selectedModelIdx, setSelectedModelIdx] = useState(0);

	const selectedModel = useMemo(() => items.find((item) => item.value === value), [items, value]);

	const fuse = useMemo(() => new Fuse(items.map((item) => ({
		...item,
		modelName: item.model?.name,
		tags: (item.model?.tags ?? []).map((tag: any) => tag.name).join(' '),
		desc: item.model?.info?.meta?.description
	})), {
		keys: ['value', 'tags', 'modelName'],
		threshold: 0.4
	}), [items]);

	const filteredItems = useMemo(() => {
		if (!searchValue.trim()) return items;
		return fuse.search(searchValue).map((result) => result.item);
	}, [searchValue, items, fuse]);

	const handleSelect = (item: any) => {
		onChange?.(item.value);
		setShow(false);
		setSearchValue('');
	};

	return (
		<div className={`relative ${className}`}>
			<button
				id={id}
				className="flex items-center gap-1 px-3 py-1.5 text-sm font-medium rounded-lg border border-gray-200 dark:border-gray-700 hover:bg-gray-100 dark:hover:bg-gray-800 transition"
				onClick={() => setShow(!show)}
			>
				<span className="truncate max-w-[200px]">
					{selectedModel?.label || placeholder || t('Select a model')}
				</span>
				<Icon name="ChevronDown" className="size-4" />
			</button>

			{show && (
				<div className="absolute top-full left-0 mt-1 w-80 max-h-96 overflow-hidden rounded-xl bg-white dark:bg-gray-900 shadow-lg border border-gray-200 dark:border-gray-700 z-50">
					<div className="p-3 border-b border-gray-100 dark:border-gray-800">
						<div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-gray-100 dark:bg-gray-800">
							<Icon name="Search" className="size-4 text-gray-500" />
							<input
								type="text"
								value={searchValue}
								onChange={(e) => setSearchValue(e.target.value)}
								placeholder={t('Search a model')}
								className="flex-1 bg-transparent outline-none text-sm"
								autoFocus
							/>
						</div>
					</div>

					<div className="p-2 max-h-72 overflow-y-auto">
						{filteredItems.length > 0 ? (
							filteredItems.map((item, idx) => (
								<ModelItem
									key={item.value}
									item={item}
									index={idx}
									selectedModelIdx={selectedModelIdx}
									value={value}
									onClick={() => handleSelect(item)}
								/>
							))
						) : (
							<div className="p-4 text-center text-sm text-gray-500">
								{t('No models found')}
							</div>
						)}
					</div>
				</div>
			)}
		</div>
	);
}

// openwebui/src/lib/components/common/Selector.svelte
<script lang="ts">
        import { Select } from 'bits-ui';

        import { flyAndScale } from '$lib/utils/transitions';

        import { createEventDispatcher } from 'svelte';
        import Icon from '$lib/components/icons/Icon.svelte';

        const dispatch = createEventDispatcher();

        export let value = '';
        export let placeholder = $i18n.t('Select a model');
        export let searchEnabled = true;
        export let searchPlaceholder = $i18n.t('Search a model');

        export let items = [
                { value: 'mango', label: 'Mango' },
                { value: 'watermelon', label: 'Watermelon' },
                { value: 'apple', label: 'Apple' },
                { value: 'pineapple', label: 'Pineapple' },
                { value: 'orange', label: 'Orange' }
        ];

        let searchValue = '';

        $: filteredItems = searchValue
                ? items.filter((item) => item.value.toLowerCase().includes(searchValue.toLowerCase()))
                : items;
</script>

<Select.Root
        {items}
        onOpenChange={() => {
                searchValue = '';
        }}
        selected={items.find((item) => item.value === value)}
        onSelectedChange={(selectedItem) => {
                value = selectedItem.value;
        }}
>
        <Select.Trigger class="relative w-full" aria-label={placeholder}>
                <Select.Value
                        class="inline-flex h-input px-0.5 w-full outline-hidden bg-transparent truncate text-lg font-semibold placeholder-gray-400  focus:outline-hidden"
                        {placeholder}
                />
                <Icon name="ChevronDown" className="absolute end-2 top-1/2 -translate-y-[45%] size-3.5" strokeWidth="2.5" />
        </Select.Trigger>
        <Select.Content
                class="w-full rounded-lg  bg-white dark:bg-gray-900 dark:text-white shadow-lg border border-gray-300/30 dark:border-gray-700/40  outline-hidden"
                transition={flyAndScale}
                sideOffset={4}
        >
                <slot>
                        {#if searchEnabled}
                                <div class="flex items-center gap-2.5 px-5 mt-3.5 mb-3">
                                        <Icon name="Search" className="size-4" strokeWidth="2.5" />

                                        <input
                                                bind:value={searchValue}
                                                class="w-full text-sm bg-transparent outline-hidden"
                                                placeholder={searchPlaceholder}
                                        />
                                </div>

                                <hr class="border-gray-100 dark:border-gray-850" />
                        {/if}

                        <div class="px-3 my-2 max-h-80 overflow-y-auto">
                                {#each filteredItems as item}
                                        <Select.Item
                                                class="flex w-full font-medium line-clamp-1 select-none items-center rounded-button py-2 pl-3 pr-1.5 text-sm  text-gray-700 dark:text-gray-100  outline-hidden transition-all duration-75 hover:bg-gray-100 dark:hover:bg-gray-850 rounded-lg cursor-pointer data-highlighted:bg-muted"
                                                value={item.value}
                                                label={item.label}
                                        >
                                                {item.label}

                                                {#if value === item.value}
                                                        <div class="ml-auto">
                                                                <Icon name="Check" />
                                                        </div>
                                                {/if}
                                        </Select.Item>
                                {:else}
                                        <div>
                                                <div class="block px-5 py-2 text-sm text-gray-700 dark:text-gray-100">
                                                        {$i18n.t('No results found')}
                                                </div>
                                        </div>
                                {/each}
                        </div>
                </slot>
        </Select.Content>
</Select.Root>
