// openwebui/src/lib/components/chat/ChatPlaceholder.svelte
<script lang="ts">
        import { WEBUI_API_BASE_URL, WEBUI_BASE_URL } from '$lib/constants';
        import { marked } from 'marked';

        import { config, user, models as _models, temporaryChatEnabled } from '$lib/stores';
        import { onMount, getContext } from 'svelte';

        import { blur, fade } from 'svelte/transition';

        import Suggestions from './Suggestions.svelte';
        import { sanitizeResponseContent } from '$lib/utils';
        import Icon from '$lib/components/icons/Icon.svelte';

        const i18n = getContext('i18n');

        export let modelIds = [];
        export let models = [];
        export let atSelectedModel;

        export let onSelect = (e) => {};

        let mounted = false;
        let selectedModelIdx = 0;

        $: if (modelIds.length > 0) {
                selectedModelIdx = models.length - 1;
        }

        $: models = modelIds.map((id) => $_models.find((m) => m.id === id));

        onMount(() => {
                mounted = true;
        });
</script>

{#key mounted}
        <div class="m-auto w-full max-w-6xl px-8 lg:px-20">
                <div class="flex justify-start">
                        <div class="flex -space-x-4 mb-0.5" in:fade={{ duration: 200 }}>
                                {#each models as model, modelIdx}
                                        <button
                                                on:click={() => {
                                                        selectedModelIdx = modelIdx;
                                                }}
                                        >
                                                ')
                                                        )}
                                                        placement="right"
                                                >
                                                        <img
                                                                src={`${WEBUI_API_BASE_URL}/models/model/profile/image?id=${model?.id}&lang=${$i18n.language}`}
                                                                class=" size-[2.7rem] rounded-full border-[1px] border-gray-100 dark:border-none"
                                                                alt="logo"
                                                                draggable="false"
                                                        />
                                                
                                        </button>
                                {/each}
                        </div>
                </div>

                {#if $temporaryChatEnabled}
                        
                                <div class="flex items-center gap-2 text-gray-500 text-lg mt-2 w-fit">
                                        {$i18n.t('Temporary Chat')}
                                </div>
                        
                {/if}

                <div
                        class=" mt-2 mb-4 text-3xl text-gray-800 dark:text-gray-100 text-left flex items-center gap-4 font-primary"
                >
                        <div>
                                <div class=" capitalize line-clamp-1" in:fade={{ duration: 200 }}>
                                        {#if models[selectedModelIdx]?.name}
                                                {models[selectedModelIdx]?.name}
                                        {:else}
                                                {$i18n.t('Hello, {{name}}', { name: $user?.name })}
                                        {/if}
                                </div>

                                <div in:fade={{ duration: 200, delay: 200 }}>
                                        {#if models[selectedModelIdx]?.info?.meta?.description ?? null}
                                                <div
                                                        class="mt-0.5 text-base font-normal text-gray-500 dark:text-gray-400 line-clamp-3 markdown"
                                                >
                                                        {@html marked.parse(
                                                                sanitizeResponseContent(
                                                                        models[selectedModelIdx]?.info?.meta?.description
                                                                ).replaceAll('\n', '<br>')
                                                        )}
                                                </div>
                                                {#if models[selectedModelIdx]?.info?.meta?.user}
                                                        <div class="mt-0.5 text-sm font-normal text-gray-400 dark:text-gray-500">
                                                                By
                                                                {#if models[selectedModelIdx]?.info?.meta?.user.community}
                                                                        <a
                                                                                href="https://openwebui.com/m/{models[selectedModelIdx]?.info?.meta?.user
                                                                                        .username}"
                                                                                >{models[selectedModelIdx]?.info?.meta?.user.name
                                                                                        ? models[selectedModelIdx]?.info?.meta?.user.name
                                                                                        : `@${models[selectedModelIdx]?.info?.meta?.user.username}`}</a
                                                                        >
                                                                {:else}
                                                                        {models[selectedModelIdx]?.info?.meta?.user.name}
                                                                {/if}
                                                        </div>
                                                {/if}
                                        {:else}
                                                <div class=" text-gray-400 dark:text-gray-500 line-clamp-1 font-p">
                                                        {$i18n.t('How can I help you today?')}
                                                </div>
                                        {/if}
                                </div>
                        </div>
                </div>

                <div class=" w-full font-primary" in:fade={{ duration: 200, delay: 300 }}>
                        <Suggestions
                                className="grid grid-cols-2"
                                suggestionPrompts={atSelectedModel?.info?.meta?.suggestion_prompts ??
                                        models[selectedModelIdx]?.info?.meta?.suggestion_prompts ??
                                        $config?.default_prompt_suggestions ??
                                        []}
                                {onSelect}
                        />
                </div>
        </div>
{/key}

// openwebui/src/components/chat/ChatPlaceholder.tsx
import React, { useState, useEffect } from 'react';
import { t } from '$lib/i18n';
import { useStore } from '$lib/stores';
import { WEBUI_VERSION } from '$lib/constants';
import { WEBUI_API_BASE_URL } from '$lib/constants';
import Suggestions from './Suggestions';

interface ChatPlaceholderProps {
	modelIds?: string[];
	models?: any[];
	atSelectedModel?: any;
	onSelect?: (e: any) => void;
}

export default function ChatPlaceholder({
	modelIds = [],
	models: propModels = [],
	atSelectedModel,
	onSelect = () => {}
}: ChatPlaceholderProps) {
	const { user, models: storeModels, temporaryChatEnabled } = useStore();
	const [mounted, setMounted] = useState(false);
	const [selectedModelIdx, setSelectedModelIdx] = useState(0);

	const models = modelIds.map((id) => storeModels.find((m: any) => m.id === id) || propModels.find((m: any) => m.id === id));

	useEffect(() => {
		setMounted(true);
	}, []);

	useEffect(() => {
		if (modelIds.length > 0) {
			setSelectedModelIdx(models.length - 1);
		}
	}, [modelIds, models.length]);

	if (!mounted) return null;

	return (
		<div className="m-auto w-full max-w-6xl px-8 lg:px-20">
			<div className="flex justify-start">
				<div className="flex -space-x-4 mb-0.5">
					{models.map((model, modelIdx) => (
						<button key={modelIdx} onClick={() => setSelectedModelIdx(modelIdx)}>
							<img
								src={`${WEBUI_API_BASE_URL}/models/model/profile/image?id=${model?.id}&lang=pl`}
								className="size-[2.7rem] rounded-full border-[1px] border-gray-100 dark:border-none"
								alt="logo"
								draggable={false}
							/>
						</button>
					))}
				</div>
			</div>

			{temporaryChatEnabled && (
				<div className="flex items-center gap-2 text-gray-500 text-lg mt-2 w-fit">
					{t('Temporary Chat')}
				</div>
			)}

			<div className="mt-2 mb-4 text-3xl text-gray-800 dark:text-gray-100 text-left flex items-center gap-4 font-primary">
				<div>
					<div className="capitalize line-clamp-1">
						{models[selectedModelIdx]?.name || t('Hello, {{name}}', { name: user?.name })}
					</div>
				</div>
			</div>

			<Suggestions
				suggestionPrompts={models[selectedModelIdx]?.info?.meta?.suggestion_prompts || []}
				onSelect={onSelect}
			/>
		</div>
	);
}
